#!/usr/bin/env php
<?php

use AlphaRock\Core\Cli\CliParser;
use AlphaRock\Core\Static\MonkeyCluster;
use AlphaRock\Core\Static\Log;
use AlphaRock\Core\Database\Query\SQL;

require_once __DIR__ . "/src/alpha-quicksight.php";


// Script Definition
$fileMap = [
    "Pre Aggregate Average for last 7 Days" => "data/refresh_avg7d.sql",
];

foreach ($fileMap as $job => $file) {
    $sql = SQL::fromFile(__DIR__ . "/../sql/" . $file);

    Log::info("Refreshing Materialized View: $job");
    $result = MonkeyCluster::query($sql);
    $queryTimeSec = round($result->getTime(), 3);
    $rowCount = $result->getRowCount();

    Log::debug("$queryTimeSec sec");
}
