#!/usr/bin/env php
<?php

use AlphaRock\Core\Cli\CliParser;
use AlphaRock\Core\Common\Time;
use AlphaRock\Core\Static\MonkeyCluster;
use AlphaRock\Core\Static\Log;
use AlphaRock\Core\Database\Query\SQL;

require_once __DIR__ . "/src/alpha-quicksight.php";

/** @var CliParser $Cli */
$day = $Cli->getOption('day', Time::today());
Time::toDate($day);


$input = <<<SQL
    SELECT '$day'::date as "ref_day"
SQL;

Log::debug("Generating 7d avg for reference day $day");;
$result = MonkeyCluster::query(SQL::fromFile(__DIR__ . "/../sql/data/generate_avg7d.sql", ['{script_input}' => $input]));
$rowCount = $result->getRowCount();
Log::debug("Created 7d avg for $day ($rowCount rows)");;

