#!/usr/bin/env php
<?php

use AlphaRock\Alpha\QuickSight\Backend\BalanceImport;
use AlphaRock\Core\Log\LogLevel;
use AlphaRock\Core\Static\Log;
use AlphaRock\Core\Static\MonkeyCluster;

require_once __DIR__ . "/../vendor/autoload.php";

Log::setLogLevel(LogLevel::DEBUG);
$lastTs = MonkeyCluster::fetchField("SELECT max(trading_minute) FROM quicksight.balance_by_minute") ?? '2025-05-17';

BalanceImport::balanceForTimestamp($lastTs, 1500);


