#!/usr/bin/env php
<?php

use AlphaRock\Core\Cli\CliParser;
use AlphaRock\Core\Static\MonkeyCluster;
use AlphaRock\Core\Static\Log;
use AlphaRock\Core\Log\LogLevel;
use AlphaRock\Core\Database\Query\SQL;

require_once __DIR__ . "/../vendor/autoload.php";

$Cli = new CliParser($argv);
if ($Cli->flagIsSet('debug')) {
    Log::setLogLevel(LogLevel::DEBUG);
}

// Script Definition
$fileMap = [
    "Exposure Data" => "data/clean_exposure.sql",
    "TradeData" => "data/clean_tradingdata.sql",
];

foreach ($fileMap as $job => $file) {
    $sql = SQL::fromFile( __DIR__ . "/../sql/" . $file);

    Log::info("Deleting old entires: $job");
    $result = MonkeyCluster::query($sql);
    $queryTimeSec = round($result->getTime(), 3);
    $rowCount = $result->getRowCount();

    Log::debug("$queryTimeSec sec");
}
