#!/usr/bin/env php
<?php

use AlphaRock\Core\Cli\CliParser;
use AlphaRock\Core\Common\Time;
use AlphaRock\Core\Static\MonkeyCluster;
use AlphaRock\Core\Static\Log;
use AlphaRock\Core\Database\Query\SQL;

require_once __DIR__ . "/src/alpha-quicksight.php";

/** @var CliParser $Cli */
$day = $Cli->getOption('day', Time::today(-1));
$n = $Cli->getOption('n', 1);
$cutOff = Time::today();


for ($i = 1; $i <= $n; $i++) {
    if($day === $cutOff) {
        Log::warning("Current Day reached. Exiting Script");
        exit;
    }
    Log::info("Generating Trading Data for $day");
    $nextDay = Time::generate($day, Time::MYSQL_DATE, "+1 day");
    $input = <<<SQL
    SELECT '$day'::timestamp as "start",
           '$nextDay'::timestamp as "end",
           '$cutOff'::timestamp as "cut_off"
    SQL;

    $sql = SQL::fromFile(__DIR__ . "/../sql/daily/generate_daily_tradingdata.sql", ['{script_input}' => $input]);
    MonkeyCluster::query($sql);

    $day = $nextDay;
}



