#!/usr/bin/env php
<?php

use AlphaRock\Alpha\QuickSight\Cryptostruct\MinuteBalanceImport;
use AlphaRock\Core\Cli\CliParser;
use AlphaRock\Core\Common\Time;
use AlphaRock\Core\Static\MonkeyCluster;
use AlphaRock\Core\Static\Log;
use AlphaRock\Core\Database\Query\SQL;


require_once __DIR__ . "/src/alpha-quicksight.php";

/** @var CliParser $Cli */
$n = $Cli->getOption('n', 61);
$lastTs = MonkeyCluster::fetchField("SELECT max(trading_minute) FROM performance.minute_exposure") ?? Time::today(-8);
$lastTs = $Cli->getOption('start', $lastTs);

Time::toFormat($lastTs, Time::MYSQL_MINUTE);

MinuteBalanceImport::balanceForTimestamp($lastTs, $n);

Log::info("Calculating PnL");;
$result = MonkeyCluster::query(SQL::fromFile(__DIR__ . "/../sql/data/generate_exposure_pnl.sql"));
$rowCount = $result->getRowCount();
Log::debug("Updated $rowCount exposure sets with PnL");;
