#!/usr/bin/env php
<?php

use AlphaRock\Core\Cli\CliParser;
use AlphaRock\Core\Common\Time;
use AlphaRock\Core\Static\MonkeyCluster;
use AlphaRock\Core\Static\Log;
use AlphaRock\Core\Log\LogLevel;
use AlphaRock\Core\Database\Query\SQL;
use AlphaRock\Core\QuickSight\QuickSightBalanceImport;

require_once __DIR__ . "/../vendor/autoload.php";

$Cli = new CliParser($argv);
if ($Cli->flagIsSet('debug')) {
    Log::setLogLevel(LogLevel::DEBUG);
}

$n = $Cli->getOption('n', 61);
$lastTs = MonkeyCluster::fetchField("SELECT max(trading_minute) FROM quicksight._exposure") ?? Time::today(-8);

QuickSightBalanceImport::balanceForTimestamp($lastTs, $n);

$result = MonkeyCluster::query(SQL::fromFile(__DIR__ . "/../sql/data/generate_exposure_pnl.sql"));
$rowCount = $result->getRowCount();
Log::debug("Updated $rowCount exposure sets with PnL");;
