#!/usr/bin/env php
<?php

use AlphaRock\Core\Cli\CliParser;
use AlphaRock\Core\Common\Time;
use AlphaRock\Core\Static\MonkeyCluster;
use AlphaRock\Core\Static\Log;
use AlphaRock\Core\Database\Query\SQL;

require_once __DIR__ . "/src/alpha-quicksight.php";

/** @var CliParser $Cli */
$day = $Cli->getOption('day', Time::today());
Time::toDate($day);
$next = Time::generate($day, Time::MYSQL_DATE, '+1 day');


$input = <<<SQL
    SELECT '$day'::TIMESTAMP(0) as "start_ts",
           '$next'::TIMESTAMP(0) as "end_ts"
SQL;

Log::debug("Aggregating Minute data for $day (7davg, tradingdata, exposure");;
$result = MonkeyCluster::query(SQL::fromFile(__DIR__ . "/../sql/data/generate_minute.sql", ['{script_input}' => $input]));
$rowCount = $result->getRowCount();
Log::debug("Created Aggregate Minute data $day ($rowCount rows)");;
