#!/usr/bin/env php
<?php

use AlphaRock\Core\Cli\CliParser;
use AlphaRock\Core\Common\Time;
use AlphaRock\Core\Static\MonkeyCluster;
use AlphaRock\Core\Static\Log;
use AlphaRock\Core\Database\Query\SQL;

require_once __DIR__ . "/src/alpha-quicksight.php";

/** @var CliParser $Cli */
$day = $Cli->getOption('day', Time::today());
Time::toDate($day);
$next = Time::generate($day, Time::MYSQL_DATE, '+1 day');

$input = <<<SQL
    SELECT '$day'::TIMESTAMP(0) as "start_ts",
           '$next'::TIMESTAMP(0) as "end_ts",
           '$day'::date as "ref_day",
           'quicksight|min' as "script_tag"
SQL;
Log::debug($input);

// DB Overload Protection
MonkeyCluster::getActiveQueryCount('quicksight|min', 1);
MonkeyCluster::getActiveQueriesForUser(null, 50);
MonkeyCluster::checkPerformance(
    thresholds:[
            "connections" => 100,
            "locks" => 6,
            "waits" => 20
        ]
);

// Minute aggregation
Log::info("Aggregating Minute data for $day (avg7d, tradingdata, exposure)");;
$result = MonkeyCluster::query(SQL::fromFile(__DIR__ . "/../sql/data/generate_minute.sql", ['{script_input}' => $input]));
$queryTimeSec = round($result->getTime(), 3);
$rowCount = $result->getRowCount();
Log::info("Created Aggregate Minute data $day ($rowCount rows)");;
Log::debug("$queryTimeSec sec");


$input = <<<SQL
    SELECT '$day'::date as "ref_day",
           'quicksight|intraday' as "script_tag"
SQL;

// Intraday
Log::info("Generate Intraday data for $day");;
$result = MonkeyCluster::query(SQL::fromFile(__DIR__ . "/../sql/data/generate_intraday.sql", ['{script_input}' => $input]));
$queryTimeSec = round($result->getTime(), 3);
Log::debug("$queryTimeSec sec");


// Intraday by exchange
Log::info("Generate Intraday by exchange for $day");;
$result = MonkeyCluster::query(SQL::fromFile(__DIR__ . "/../sql/data/generate_intraday_by_exchange.sql", ['{script_input}' => $input]));
$queryTimeSec = round($result->getTime(), 3);
Log::debug("$queryTimeSec sec");
