#!/usr/bin/env php
<?php

use AlphaRock\Core\Log\LogLevel;
use AlphaRock\Core\Static\Log;
use AlphaRock\Core\Static\MonkeyCluster;

require_once __DIR__ . "/../vendor/autoload.php";

Log::setLogLevel(LogLevel::DEBUG);

// Script Definition
$fileMap = [
    "top" => "intraday/refresh_intraday_top_instruments.sql",
    "intraday" => "intraday/refresh_intraday.sql",
    "intradayExchange" => "intraday/refresh_intraday_by_exchange.sql",
    "tradingdata" => "data/generate_tradingdata_by_min.sql",
];

// Get the Script to run
$availableScripts = json_encode($fileMap, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT);
$job = $argv[1] ?? 'empty';
if ($job === 'empty') {
    Log::error("SQL script must be set. Available commands: \n{$availableScripts}");
    exit;
}

foreach (array_slice($argv, 1) as $job) {
    print "\n\n";
    if (!array_key_exists($job, $fileMap)) {
        Log::error("'$job' is no valid SQL script. Available commands:");
        continue;
    }
    $sql = file_get_contents(__DIR__ . "/../sql/" . $fileMap[$job]);

// Run the script
    Log::info("Executing SQL script: {$fileMap[$job]}");
    $result = MonkeyCluster::query($sql);
    $queryTimeSec = round($result->getTime(), 3);
    $rowCount = $result->getRowCount();

    Log::info("$rowCount rows affected / $queryTimeSec sec");
}

