#!/usr/bin/env php
<?php

use AlphaRock\Core\Cli\CliParser;
use AlphaRock\Core\Common\Time;
use AlphaRock\Core\Database\Query\SQL;
use AlphaRock\Core\Log\LogLevel;
use AlphaRock\Core\Static\Log;
use AlphaRock\Core\Static\MonkeyCluster;

require_once __DIR__ . "/../vendor/autoload.php";

$Cli = new CliParser($argv);
if ($Cli->flagIsSet('debug')) {
    Log::setLogLevel(LogLevel::DEBUG);
}

// Replacements
$start = Time::today();
$end = Time::today(+1);

Log::info("Updating full day TradeData for $start");
$scriptInput = <<<SQL
    SELECT CURRENT_TIMESTAMP::timestamp as "now",
           CURRENT_DATE::timestamp as "today",
           '$start'::timestamp as "start",
           '$end'::timestamp as "end"
SQL;

Log::debug("\n$scriptInput");


$sql = SQL::fromFile(
    filepath: __DIR__ . "/../sql/data/generate_tradingdata.sql",
    replacements: ['{script_input}' => $scriptInput]
);

// Run the script
$result = MonkeyCluster::query($sql);
$queryTimeSec = round($result->getTime(), 3);
$rowCount = $result->getRowCount();

Log::info("$rowCount rows affected / $queryTimeSec sec");
